CREATE TABLE "User"
(
    "Username" CHARACTER VARYING(30) PRIMARY KEY,
    "Role" Integer NOT NULL,
    "PasswordHash" CHARACTER VARYING(64) NOT NULL,
    "PasswordSalt" CHARACTER VARYING(64) NOT NULL
);

CREATE TABLE "Test"
(
    "Id" UUID PRIMARY KEY,
    "Title" CHARACTER VARYING(100) NOT NULL,
    "Description" CHARACTER VARYING(1000) NOT NULL,
    "Username" CHARACTER VARYING(30) REFERENCES "User" ("Username") NOT NULL
);

CREATE TABLE "Question"
(
    "Id" UUID PRIMARY KEY,
    "String" CHARACTER VARYING(200) NOT NULL,
    "TestId" UUID REFERENCES "Test"("Id") ON DELETE CASCADE
);

CREATE TABLE "Option"
(
    "Id" UUID PRIMARY KEY,
    "String" CHARACTER VARYING(100) NOT NULL,
    "QuestionId" UUID REFERENCES "Question"("Id") ON DELETE CASCADE
);
